### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by yeoonjae** [f-lab-edu/DoorRush#4]
# 사용자 회원가입 기능

## 구현상세기능

 - [x] 회원가입 요청 시 전달 받은 데이터의 유효성 검사
 - [x] 중복ID 검사 기능
 - [x] 회원 테이블에 insert 

## 💡 학습할 내용

- 학습할 내용을 작성합니다.

**Comment by f-lab-jd** [comment]
1. 회원 테이블에 insert
